# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            A.J.
tagline:          'A developer blog'
description:      'A developer blog for me and my thoughts'
url:              http://ajkueterman.com
baseurl:          /

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

author:
  name:           'A.J. Kueterman'
  url:            https://twitter.com/ajkueterman

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/robotsquidward
