# Site settings
title: A.J. Kueterman
email: aj@ajkueterman.com
description: Development, design, film, television, music, culture, science, art, and all of those other good things.  This is my personal blog, we'll see what it becomes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ajkueterman.com" # the base hostname & protocol for your site
twitter_username: ajkueterman
github_username:  robotsquidward
include: ['_pages']
# Build settings
markdown: kramdown
